### ISSUE TITLE
运行时不报错闪退

### ISSUE THREAD

**Issue by shijiu1** [CyanideCN/PyCINRAD#107]
在安装好后运行程序，跳出窗口，选择完雷达文件后，点击绘制会在这个界面闪退
![image](https://github.com/CyanideCN/PyCINRAD/assets/40565702/02535783-9299-48ce-9f52-88a978f25114)
返回Process finished with exit code -1073740791 (0xC0000409)，求帮助

**Comment by CyanideCN** [comment]
GUI脚本已经不再维护了
