### ISSUE TITLE
get_data(tilt, drange, dtype) 中，如何给 drange 取一个合理的值？

### ISSUE THREAD

**Issue by Xunius** [CyanideCN/PyCINRAD#113]
开发者好，

我想问一下在
```
f.get_data(tilt, drange, dtype) #Get data
```

这个命令中， `drange` 参数如何选取一个合理的数值？我注意到很多示例中都直接给定了 `230` 这个数值。如何在尚未读取全部数值的情况下，获知某个雷达的数据有效半径是多少，然后用这个有效数值半径去调用 `get_data()` 方法？比如类似这样：

```
max_range = f.get_effective_range(tilt)
data = f.get_data(tilt, max_range, 'REF')
```

谢谢

**Comment by CyanideCN** [comment]
`StandardData.scan_config[i].max_range1`可以获取扫描半径，单位为米

**Comment by Xunius** [comment]
@CyanideCN 感谢回复。
我想进一步确认一下， `StandardData.scan_config[i].max_range1` 之中的 `i` 是仰角序号吗？

因为我在打开一个基数据文件时，发现 `f.scan_config` 是一个长度为11的list，但是 `f.angleindex_r` 是一个长度为9的list，且数值为 `[0, 2, 4, 5, 6, 7, 8, 9, 10]`。

而且，`f.scan_config[0]` 和 `f.scan_config[1]` 中给出的 `elev` 都是 0.48339844，但是 `f.scan_config[0].max_range1` 是 460000，`f.scan_config[1].max_range1` 是 230000。

所以，我在使用 `f.scan_config[i].max_range1` 的时候，`i` 应该是`[0, 2, 4, 5, 6, 7, 8, 9, 10]` 其中的一个吗？
