### ISSUE TITLE
天气雷达组网产品数据格式更新

### ISSUE THREAD

**Issue by CyanideCN** [CyanideCN/PyCINRAD#13]
根据中国气象局预报与网络司，从10月8日开始组网产品NetCDF标准格式数据的试用。`cinrad.io`模块需要改动，同时分发格点化之后的数据也可以解决 #7 和 #8 的问题。
![default](https://user-images.githubusercontent.com/40656756/45811937-07e70e00-bd01-11e8-9e2a-d7cab17f7fc8.png)
![default](https://user-images.githubusercontent.com/40656756/45812020-3a910680-bd01-11e8-9754-05417c0fe3fc.png)

**Comment by zxdawn** [comment]
That's nice!
