### ISSUE TITLE
请问CINRAD版本问题

### ISSUE THREAD

**Issue by wcwoo** [CyanideCN/PyCINRAD#30]
您好！请问这个项目的源代码是对应 [天气雷达基数据标准格式（试用）] 2015-10版本的吗？

**Comment by CyanideCN** [comment]
你说的这个格式应该对应的是`cinrad.io.StandardData`这个类

**Comment by wcwoo** [comment]
谢谢！我们会尝试用来解读雷达档案。

请问您是气象局的同行吗？
