### ISSUE TITLE
使用PPI绘制PUP基反产品出错

### ISSUE THREAD

**Issue by laishenggx** [CyanideCN/PyCINRAD#35]
```
from cinrad.io import PUP
from cinrad.visualize.ppi import PPI

f=PUP('C:\\pyproj\\cinrad\\pupdata\\R\\19\\20170330.084822.01.19.778')
data=f.get_data()
print(data.data.shape)
fig = PPI(data)
fig('C:\\pyproj\\cinrad\\')
```

编译环境：WIN10+python3.7
库：matplotlib(3.0.3)、cartopy(0.17.0)
雷达信息：河池雷达(Z9778)，PUP基本反射率因子产品(R,19)

此时解释器提示
```
C:\Users\win\Anaconda3\python.exe C:/pyproj/cinrad/pup_ppi.py

Traceback (most recent call last):
  File "C:/pyproj/cinrad/pup_ppi.py", line 8, in <module>
    fig = PPI(data)
  File "C:\Users\win\Anaconda3\lib\site-packages\cinrad\visualize\ppi.py", line 94, in __init__
    self._plot(**kwargs)
  File "C:\Users\win\Anaconda3\lib\site-packages\cinrad\visualize\ppi.py", line 148, in _plot
    self.geoax.pcolormesh(lon, lat, var, norm=pnorm, cmap=pcmap, **kwargs)
  File "C:\Users\win\Anaconda3\lib\site-packages\cartopy\mpl\geoaxes.py", line 1459, in pcolormesh
    result = self._pcolormesh_patched(*args, **kwargs)
  File "C:\Users\win\Anaconda3\lib\site-packages\cartopy\mpl\geoaxes.py", line 1491, in _pcolormesh_patched
    X, Y, C = self._pcolorargs('pcolormesh', *args, allmatch=allmatch)
  File "C:\Users\win\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 5575, in _pcolorargs
    C.shape, Nx, Ny, funcname))
TypeError: Dimensions of C (366, 230) are incompatible with X (366) and/or Y (230); see help(pcolormesh)

Process finished with exit code 1
```
后来我输出了data.lon、data.lat以及data.data的shape
发现是由于data.data的shape是(366, 230)
而data.lon和data.lat则是(230, 366)
初步判断是绘图时X，Y和C的数组形状不一样

于是尝试对\cinrad\visualize\ppi.py的第148行进行修改，将var进行转置
self.geoax.pcolormesh(lon, lat, **var.T**, norm=pnorm, cmap=pcmap, **kwargs)
修改之后程序可以正常运行，但是雷达图像不是正确的

**Comment by CyanideCN** [comment]
我觉得可能是生成经纬度数据的时候出了问题，方位角和距离是手动生成的，也许形状出错了。
https://github.com/CyanideCN/PyCINRAD/blob/master/cinrad/io/io.py#L669

**Comment by laishenggx** [comment]
> 我觉得可能是生成经纬度数据的时候出了问题，方位角和距离是手动生成的，也许形状出错了。
> https://github.com/CyanideCN/PyCINRAD/blob/master/cinrad/io/io.py#L669

请问有没有示例的脚本呀？或者说是用法说明的

**Comment by CyanideCN** [comment]
用法在README里面有，PUP(cinrad.io.io.PUP)这部分确实一直都有问题，我也不打算弄了，你有兴趣可以看一下




------------------ 原始邮件 ------------------
发件人: "laishenggx"<notifications@github.com>; 
发送时间: 2019年5月16日(星期四) 中午11:36
收件人: "CyanideCN/PyCINRAD"<PyCINRAD@noreply.github.com>; 
抄送: "Du"<274555447@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [CyanideCN/PyCINRAD] 使用PPI绘制PUP基反产品出错 (#35)



 
我觉得可能是生成经纬度数据的时候出了问题，方位角和距离是手动生成的，也许形状出错了。
 https://github.com/CyanideCN/PyCINRAD/blob/master/cinrad/io/io.py#L669
  
请问有没有示例的脚本呀？或者说是用法说明的

**Comment by laishenggx** [comment]
好的谢谢

**Comment by CyanideCN** [comment]
已修复
