### ISSUE TITLE
绘制PUP基本速度产品时单位错误

### ISSUE THREAD

**Issue by laishenggx** [CyanideCN/PyCINRAD#37]
雷达信息：河池雷达(Z9778)，PUP基本速度产品(V,26)

使用PyCINRAD的PUP接口绘制基本速度时，发现和PUP中的不一致，后来发现是单位没有转换的问题，文件里边数据的单位是节(knots)。

![Z9778_20170330093021_1 5_115 0_VEL](https://user-images.githubusercontent.com/47738665/60555726-c6e05780-9d70-11e9-92a0-d16f1b67c0f7.png)

![PUP](https://user-images.githubusercontent.com/47738665/60555735-cf389280-9d70-11e9-8161-05ff04ab1678.png)

**Comment by CyanideCN** [comment]
好的，马上修复

**Comment by CyanideCN** [comment]
我用其他数据试了一下，并没有出现这个问题
![1](https://user-images.githubusercontent.com/40656756/60560516-b507b000-9d82-11e9-8fae-092041b454ae.png)

**Comment by laishenggx** [comment]
> 我用其他数据试了一下，并没有出现这个问题

嗯嗯，应该是我们RPG处理的时候还是用的knots，谢谢了

**Comment by CyanideCN** [comment]
从你那个图来看，我觉得是颜色映射出问题了，有几个色阶被跳过了，连过渡都没有

**Comment by laishenggx** [comment]
> 从你那个图来看，我觉得是颜色映射出问题了，有几个色阶被跳过了，连过渡都没有

我试着用metpy.io.level3file的接口试着自己读取并画图了一下，发现应该还是单位的问题，颜色映射(norm)应该是正确的。

没有转换前：
![sample1_V26](https://user-images.githubusercontent.com/47738665/60561340-c30b0000-9d85-11e9-8628-bac2ce8c0366.png)

转换后：
![sample_V26](https://user-images.githubusercontent.com/47738665/60561077-dff30380-9d84-11e9-9bd6-f5af55762971.png)

**Comment by laishenggx** [comment]
这个是上图的pup数据文件：
[20170330.093021.02.26.778.txt](https://github.com/CyanideCN/PyCINRAD/files/3353134/20170330.093021.02.26.778.txt)

**Comment by CyanideCN** [comment]
好的
