### ISSUE TITLE
你好，请问该库能绘制透明背景，不要地图的png图片吗？

### ISSUE THREAD

**Issue by toocf** [CyanideCN/PyCINRAD#38]

**Comment by CyanideCN** [comment]
不直接支持此功能，不过你可以读取了数据之后用matplotlib自己画

**Comment by toocf** [comment]
好的，python不太熟悉，新项目接手，没思路

**Comment by toocf** [comment]
作者您好，我有雷达数据，想将一个省的多台雷达数据合并到一个地图上。
效果就是这样：http://www.nmc.cn/publish/radar/chinaall.html
范围是某个省份的，您能解决吗？
有偿的方式请您解决下：微信 geciki

**Comment by CyanideCN** [comment]
可以
