### ISSUE TITLE
雷达数据格点化的问题

### ISSUE THREAD

**Issue by CyanideCN** [CyanideCN/PyCINRAD#4]
目前的思路是使用scipy.interpolate.griddata来进行3维插值，我在_grid()里也进行了尝试，但是插值出来的格点除了第一层其他完全不符。

**Comment by Mo-Dabao** [comment]
方便QQ交流吗？我暑假也要做这方面的东西

**Comment by CyanideCN** [comment]
好，我QQ是274555447 @Mo-Dabao

**Comment by zxdawn** [comment]
可以试试scipy.stats.binned_statistic_dd系列。我之前用
scipy.stats.binned_statistic_2d算组合反射率的，速度有点慢。
你也可以看看pyart里面怎么处理的。

**Comment by CyanideCN** [comment]
目前基本确定是nearest插值方式所造成的失真，但是其他方法内存和时间都耗费巨大。目前_grid_3d函数是用的这个方法，这个函数会保留但不会继续更新。
