### ISSUE TITLE
读沈阳的雷达数据报错，ValueError

### ISSUE THREAD

**Issue by Apolloay** [CyanideCN/PyCINRAD#40]
您好，我是小白，打扰了。
读沈阳的数据时出现报错，“ValueError: year 16188 is out of range”
请指点，十分感谢。

**Comment by CyanideCN** [comment]
东北的雷达格式和标注的格式不太一样， #6 #39 都是一样的问题。现在问题在于没有数据说明可以参考。

**Comment by CyanideCN** [comment]
如果数据量小的话，可以发到我邮箱里面，我用软件帮你转成标准格式

**Comment by YvZheng** [comment]
我也遇到了同样的问题，我有少量的沈阳雷达的基数据，文件上注明是SC格式，按照SC格式根本无法读取

**Comment by CyanideCN** [comment]
最新版本应当可以读取沈阳雷达数据了，你可以试一下，如果还有问题的话可以重新开issue
