### ISSUE TITLE
小白预报员请教

### ISSUE THREAD

**Issue by liyuan3970** [CyanideCN/PyCINRAD#44]
您好，非常感谢你的这个雷达库，请问您这个python库的RHI图案例怎么画，看readme没有看懂。。。。

**Comment by CyanideCN** [comment]
那张RHI图是雷达的RHI扫描模式数据绘制出来的，如果你想要做剖面的话请用cinrad.easycalc.VCS

**Comment by liyuan3970** [comment]
哦哦，那个我是会的，谢谢啦





------------------ 原始邮件 ------------------
发件人: CyanideCN <notifications@github.com&gt;
发送时间: 2019年10月1日 00:55
收件人: CyanideCN/PyCINRAD <PyCINRAD@noreply.github.com&gt;
抄送: liyuan3970 <857956255@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[CyanideCN/PyCINRAD] 小白预报员请教 (#44)




那张RHI图是雷达的RHI扫描模式数据绘制出来的，如果你想要做剖面的话请用cinrad.easycalc.VCS
