### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by liyuan3970** [CyanideCN/PyCINRAD#46]
您好，看您的pycinrad里面有合成雷达拼图的函数，我自己看源码 easycalc的GridMapper类，没有理解。。。不知道这个怎样传参数才能处理拼图，我用的是“Z_RADR_I_Z9576_20190810000600_O_DOR_SA_CAP.bin.bz2”这样的数据，新手小白，照着您的文档一步一步来学，请多指教，或给一个雷达拼图绘图的demo，感激不尽！

**Comment by CyanideCN** [comment]
Issue区域不是专门用来问怎么用的，关于使用方面的问题你可以加我QQ，274555447
