### ISSUE TITLE
get_range函数对于CD雷达可能存在BUG

### ISSUE THREAD

**Issue by lovechang1986** [CyanideCN/PyCINRAD#47]
对于个别CD雷达，Rreso=0.3,drange=1000；
得到的结果与反射率的数组shape就不一致。

**Comment by lovechang1986** [comment]
这个读取类似沈阳雷达的处理还不能放在处理SA雷达的函数下面，SA雷达下面首先是扫描了一个仰角的反射率，然后同仰角的速度谱，在扫描一个仰角的反射率、然后同仰角的速度谱，之后才是每个仰角同时扫描；所以当np.delete(..., [1,3])的时候实际上相当于减少了2个仰角。

我觉得应该在处理CD下面增加一个文件大小的判断，之后再按照这个来处理，可能会更好一些。

**Comment by CyanideCN** [comment]
可以放在SA函数里，只用补一个类型判断
