### ISSUE TITLE
Proj

### ISSUE THREAD

**Issue by CuiHaoXuan** [CyanideCN/PyCINRAD#49]
command: /srv/conda/envs/notebook/bin/python /srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp2lgtr35q
       cwd: /tmp/pip-install-oedtv90z/cartopy
  Complete output (3 lines):
  setup.py:171: UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.
    '.'.join(str(v) for v in GEOS_MIN_VERSION), ))
  Proj 4.9.0 must be installed.

**Comment by CuiHaoXuan** [comment]
请问，这歌怎么解决啊

**Comment by CyanideCN** [comment]
```
apt-get install libproj-dev proj-data proj-bin
apt-get install libgeos-dev
```
