### ISSUE TITLE
能否更多地支持雷达PUP格式文件

### ISSUE THREAD

**Issue by qinglonger** [CyanideCN/PyCINRAD#53]
好像目前只支持径向类的PUP文件，能否扩大到所有类型的PUP文件呀，谢谢啦。

**Comment by CyanideCN** [comment]
格点类的文件在计算经纬度的时候有困难，以后也许会添加

**Comment by CyanideCN** [comment]
添加了CR，ET和VIL等格点类型数据的读取，其他的应该不会再添加了
