### ISSUE TITLE
如何叠加等值线图

### ISSUE THREAD

**Issue by zhaobudaola** [CyanideCN/PyCINRAD#54]
您好，请问在用cinrad.visualize.PPI画ZDR的时候如何叠加REF的等值线图呢？

**Comment by CyanideCN** [comment]
```python
fig = cinrad.visualize.PPI(zdr)
fig.geoax.contour(r.lon, r.lat, r.data)
```

**Comment by zhaobudaola** [comment]
按这个画了还是没有等值线

**Comment by CyanideCN** [comment]
更新：
少了transform参数
fig.geoax.contour(r.lon, r.lat, r.data, **transform=fig.data_crs**)
问题已解决

**Comment by zhaobudaola** [comment]
多谢，另外请问垂直剖面的话可以实现吗？看了一下没有geoax

**Comment by CyanideCN** [comment]
垂直剖面现在是不能实现的

**Comment by zhaobudaola** [comment]
好的非常感谢

**Comment by zhaobudaola** [comment]
另外求教一下画速度的垂直剖面出错，不知道是什么原因
Warning (from warnings module):
  File "D:\Anaconda3\lib\site-packages\cinrad-1.5-py3.7-win-amd64.egg\cinrad\io\level2.py", line 655
    warnings.warn("Empty data", RuntimeWarning)
RuntimeWarning: Empty data

**Comment by CyanideCN** [comment]
目前没有计划支持速度剖面哈

**Comment by zhaobudaola** [comment]
已经很强大了，感谢回复
