### ISSUE TITLE
沈阳雷达数据格式

### ISSUE THREAD

**Issue by CyanideCN** [CyanideCN/PyCINRAD#6]
![default](https://user-images.githubusercontent.com/40656756/45029508-72e6e280-b07b-11e8-905d-0ca47dafbfe3.png)
在中国气象数据网上看到沈阳雷达是SC雷达，但是用THREDDS读取时提示为SA雷达。
![default](https://user-images.githubusercontent.com/40656756/45029541-96119200-b07b-11e8-9c20-5039e4044ce8.png)
但是这个雷达的参数并不符合SA雷达的参数，在以SA雷达读取时没有报错但是读出来的数据完全不对。
（此雷达库长250m，库数1000个）

**Comment by CyanideCN** [comment]
这个基数据在101-109字节并不是CINRAD/SC或CINRAD/CD，所以排除SCD类型。同时，在117-125字节不是CINRAD/CC，排除CD类型。该文件长度为10147680字节，并不能被SAB雷达单个数据块的2432字节整除，也不能被CAB雷达单个数据块4132字节整除，所以也不是SAB或者CAB类型。现在完全不知道这个基数据是什么类型的。

**Comment by zhaopingsun** [comment]
沈阳是784厂的，型号是SC

**Comment by 1782005668** [comment]
请问，您上边贴出来的数据图，是用什么软件打开的啊

**Comment by lovechang1986** [comment]
Mi4是可以读取的，据说是3132字节和ws88d的2432很像，但格式还是有所差别。用mi4读取9个仰角，360根Ray，同时算了一下距离库大概160km左右，只能这么推断，我在气象家园问了，但还没回复。我觉得最终解决只能是问问开发mi4的人，找找这个格式。

**Comment by CyanideCN** [comment]
@lovechang1986 刚刚试了一下，文件头应该是SAB系列的
![1](https://user-images.githubusercontent.com/40656756/65811521-86755780-e16e-11e9-8a40-c66f8fbc6fa7.png)

**Comment by lovechang1986** [comment]
:+1:，这是16字节的文件头？你看我在气象家园的悬赏，我安装3132字节全部都是数据，可视化后中间有一部分就是很大的，这部分应该就是文件头，还有2圈很像的我也不知道是啥了。

**Comment by lovechang1986** [comment]
只是不知道为什么还要2圈重复的。如果搞明白这个，这个格式就算是强行破解了:joy:

**Comment by CyanideCN** [comment]
@lovechang1986 我按照气象家园那人说的规则试了一下，和SAB文件规则一样，应该算是解决了，我整理一下代码然后更新:laughing:
![Z9240_20190917072000_0 5_150_REF](https://user-images.githubusercontent.com/40656756/65811702-5c716480-e171-11e9-95c9-5a527514509d.png)

**Comment by lovechang1986** [comment]
:+1:

**Comment by lovechang1986** [comment]
强大，现在电脑没有互联网，等你更新

**Comment by CyanideCN** [comment]
@lovechang1986 新的模块whl可以在[appveyor](https://ci.appveyor.com/project/CyanideCN/pycinrad/builds/27731444/job/856uwc5p66abc9a1/artifacts)下载，从github拉取自己编译也行
