### ISSUE TITLE
安装了cinrad后，提示使用cinrad.calc.VCS ，但是无法继续运行， 也不提示错误信息。       

### ISSUE THREAD

**Issue by ty19940610** [CyanideCN/PyCINRAD#62]
在pycharm安装了cinrad1.6.0后，画剖面图提示使用cinrad.calc.VCS（ref） ，但是无法继续运行，也无法使用cinrad.easycalc.VCS（ref）， 也不提示错误信息。   
另外，求一份在VS2019中的安装教程。因为之前在安装过程中最后要求安装Proj 4.7以上，不会安装。

**Comment by CyanideCN** [comment]
没有错误信息的话我也没有办法。如果配置环境有困难的话建议用conda。
