### ISSUE TITLE
双偏振雷达数据问题

### ISSUE THREAD

**Issue by cmaMrSober** [CyanideCN/PyCINRAD#68]
大神，使用双偏振雷达基数据生成组合反射率时，圆圈外面会出现红色边缘，正好凑成一个方形，是双偏振数据不一样导致的吗？

**Comment by CyanideCN** [comment]
有图吗

**Comment by cmaMrSober** [comment]
[http://bbs.06climate.com/forum.php?mod=redirect&goto=findpost&ptid=66878&pid=1090459&fromuid=85029](url)

**Comment by CyanideCN** [comment]
可以发一下数据吗，邮箱274555447@qq.com

**Comment by boyucjz** [comment]
> 大神，使用双偏振雷达基数据生成组合反射率时，圆圈外面会出现红色边缘，正好凑成一个方形，是双偏振数据不一样导致的吗？

请问有双偏振雷达PUP文件格式说明吗？

问题详细描述：
https://github.com/CyanideCN/PyCINRAD/issues/67#issue-678994733

**Comment by cmaMrSober** [comment]
> > 大神，使用双偏振雷达基数据生成组合反射率时，圆圈外面会出现红色边缘，正好凑成一个方形，是双偏振数据不一样导致的吗？
> 
> 请问有双偏振雷达PUP文件格式说明吗？
> 
> 问题详细描述：
> [#67 (comment)](https://github.com/CyanideCN/PyCINRAD/issues/67#issue-678994733)

没有诶，要找厂家问问

**Comment by cmaMrSober** [comment]
请问大神是基数据的问题吗？

**Comment by CyanideCN** [comment]
已修复
