### ISSUE TITLE
保存图片不显示gridlines问题

### ISSUE THREAD

**Issue by hehuan710** [CyanideCN/PyCINRAD#73]
fig.gridlines()
fig(out_+list1+".png") #保存的图片不显示经纬度
plt.show()#在编译器出图有经纬度
![QQ截图20201030092521](https://user-images.githubusercontent.com/21091848/97649303-f51f9580-1a91-11eb-8842-cd897fd50737.png)
![QQ截图20201030092551](https://user-images.githubusercontent.com/21091848/97649307-f6e95900-1a91-11eb-84df-70d20e1fd931.png)

**Comment by CyanideCN** [comment]
这个是figsize设置不同的缘故，这个坐标理论上是在图外面的，直接保存是看不到的

**Comment by hehuan710** [comment]
找到一个解决办法bbox_inches='tight'

fig._text_before_save()#使用自带的保存方法才会调用改函数，故手动调用
fig.fig.savefig("111.png",bbox_inches='tight')
