### ISSUE TITLE
多普勒速度RF

### ISSUE THREAD

**Issue by yliu1yb** [CyanideCN/PyCINRAD#74]
如何取消显示多普勒速度图上RF色块

**Comment by CyanideCN** [comment]
把返回的Dataset里面的RF这一个变量删了就不会画了

**Comment by yliu1yb** [comment]
> 把返回的Dataset里面的RF这一个变量删了就不会画了
> 
> ```python
> v = f.get_data(1, 230, 'VEL')
> del v['RF']
> fig = cinrad.visualize.PPI(v)
> ```

**Comment by yliu1yb** [comment]
谢谢，我还想请问，上面代码实现将雷达径向风速图画在地图上，有将雷达极坐标转为经纬度再画吗？
`f = CinradReader(radar_file) #老版本数据
v = f.get_data(3, 230, 'VEL')
fig = cinrad.visualize.PPI(v, dpi=75)#, cmap = cmap, norm = norm`

**Comment by yliu1yb** [comment]
谢谢，我还想请问，下面代码实现将雷达径向风速图画在地图上，有将雷达极坐标转为经纬度再画吗？
`f = CinradReader(radar_file) #老版本数据 
v = f.get_data(3, 230, 'VEL') 
fig = cinrad.visualize.PPI(v, dpi=75)#, cmap = cmap, norm = norm`
