### ISSUE TITLE
雷达PPI图，数据坐标问题

### ISSUE THREAD

**Issue by yliu1yb** [CyanideCN/PyCINRAD#75]
- 你好，下面代码实现将雷达径向风速图画在地图上，有将雷达极坐标转为经纬度坐标再画吗？

- 我看到画出来的色块是等距的，但叠在经纬度地图上，伴随着纬度的增大，等经度的距离是减小的，因此画的PPI图应该是扁的才对？

```
f = CinradReader(radar_file) #老版本数据 
v = f.get_data(3, 230, 'VEL') 
fig = cinrad.visualize.PPI(v, dpi=75)
```

**Comment by CyanideCN** [comment]
返回的数据里面有转换为经纬度的
PPI的投影是等距方位投影，所以会是正圆形

**Comment by yliu1yb** [comment]
> 返回的数据里面有转换为经纬度的
> PPI的投影是等距方位投影，所以会是正圆形

好的，谢谢！
