### ISSUE TITLE
站点缺经纬度求助

### ISSUE THREAD

**Issue by danchunxiaokeai** [CyanideCN/PyCINRAD#76]
![Z9421_20201115150103_0 5_230_REF](https://user-images.githubusercontent.com/75973631/102679069-b2538180-41e7-11eb-8c72-5c97173ebee0.png)
![Z9455_20201116024724_0 5_230_REF](https://user-images.githubusercontent.com/75973631/102679072-b41d4500-41e7-11eb-9e07-09a552c07271.png)
![QQ图片20201219104900](https://user-images.githubusercontent.com/75973631/102679090-e464e380-41e7-11eb-9d28-b67510188513.png)
老师不好意思打扰了，我最近在用cinrad画雷达。出现反射率画出来了以及时间输出也对，但是站点经纬度没有的问题。我猜测可能是cinrad里一些小站点或者新站点的经纬度没有收录。想请教一下是否我可以自己修改源代码的站点经纬度设置可能可以解决这个问题。

**Comment by CyanideCN** [comment]
我之后会把站点数据换成json格式，这样方便编辑一些，目前的话你可以用f.stationlat = ... 和f.stationlon = ... 来手动设置

**Comment by danchunxiaokeai** [comment]
谢谢老师的解答！祝好！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CyanideCN/PyCINRAD"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月19日(星期六) 中午12:43
收件人:&nbsp;"CyanideCN/PyCINRAD"<PyCINRAD@noreply.github.com&gt;;
抄送:&nbsp;"黄子怡"<ziyi57@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CyanideCN/PyCINRAD] 站点缺经纬度求助 (#76)





 
我之后会把站点数据换成json格式，这样方便编辑一些，目前的话你可以用f.stationlat = ... 和f.stationlon = ... 来手动设置
