### ISSUE TITLE
读取上海南汇雷达数据错误

### ISSUE THREAD

**Issue by wwwnnn** [CyanideCN/PyCINRAD#77]
您好，请教问题，上海南汇雷达数据，用standardData读取时提示不是新标准数据，使用CinradReader读取时报错，错误如图。文件大小28兆，文件名Z_RADR_I_Z9210_**************_O_DOR_SA_CAP.bin
![image](https://user-images.githubusercontent.com/39585450/110259007-6cd17400-7fe0-11eb-927d-bd72f42e8583.jpg)

**Comment by CyanideCN** [comment]
南汇雷达用的是美国nexrad格式，建议用pyart处理。或者可以用cinrad 1.5.1或之前的版本，里面有个`cinrad.io.NexradL2Data`类，用法和现有的两个类是基本一致的。

**Comment by wwwnnn** [comment]
非常感谢大神！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CyanideCN/PyCINRAD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 下午2:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CyanideCN/PyCINRAD] 读取上海南汇雷达数据错误 (#77)





 
南汇雷达用的是美国nexrad格式，建议用pyart处理。或者可以用cinrad 1.5.1或之前的版本，里面有个cinrad.io.NexradL2Data类，用法和现有的两个类是基本一致的。
