### ISSUE TITLE
fig.plot_cross_section(sec)

### ISSUE THREAD

**Issue by taort** [CyanideCN/PyCINRAD#79]
error:

  File "/.../cinrad/visualize/ppi.py", line 319, in plot_cross_section
    "Adding cross section dynamically is not supported ininline backend, add section keyword when initializing PPI instead.''

**Comment by CyanideCN** [comment]
错误信息里已经说了，你要在诸如jupyter notebook里面画剖面的话请在实例化PPI的时候加入section参数，而不是fig.plot_cross_section
