### ISSUE TITLE
C 波段数据解析

### ISSUE THREAD

**Issue by luckydog5** [CyanideCN/PyCINRAD#83]
想问一下，是否支持C波段雷达数据解析。

**Comment by cjxytd** [comment]
您好，您的信件我已经收到，谢谢来信。

**Comment by CyanideCN** [comment]
可以的

**Comment by luckydog5** [comment]
那是用哪个方法呢？cinrad.io.StandardData直接读取CC格式雷达数据，报错

RadarDecodeError: Invalid standard data

**Comment by CyanideCN** [comment]
那试一下`cinrad.io.CinradReader`

**Comment by luckydog5** [comment]
好像是方法不支持

NotImplementedError: Only VPPI scan mode is supported

**Comment by CyanideCN** [comment]
你的数据文件名长啥样

**Comment by luckydog5** [comment]
Z_RADR_I_Z9993_20220314165224_O_DOR_CC_CAP_FMT.bin.bz2
这种

**Comment by CyanideCN** [comment]
那你这个应该是标准格式啊，`StandardData`打不开吗

**Comment by luckydog5** [comment]
打不开，Invalid standard data
报这个错误，我把文件传上来，你看能用什么方法解析下
[Z_RADR_I_Z9993_20220314165224_O_DOR_CC_CAP_FMT.bin.bz2.zip](https://github.com/CyanideCN/PyCINRAD/files/8281225/Z_RADR_I_Z9993_20220314165224_O_DOR_CC_CAP_FMT.bin.bz2.zip)

**Comment by CyanideCN** [comment]
你这个数据应该有点问题，文件头都不对

**Comment by luckydog5** [comment]
不应该啊，这是从资源池正常拿的数据

**Comment by CyanideCN** [comment]
你用其他软件能打开吗
