### ISSUE TITLE
速度产品切面图比实际用pup的图海拔要高

### ISSUE THREAD

**Issue by liyuan3970** [CyanideCN/PyCINRAD#84]
前辈我最近用您的模块画图的时候发现速度产品切面图比实际用pup的图海拔要高，我用的时.14版本代码如下，不知道问题出在哪里.............

ax3 = plt.axes(rect3)
rl = [f.get_data(i, 230, 'VEL') for i in f.angleindex_r]
vcs_r = cinrad.easycalc.VCS(rl)
s1 = vcs_r.get_section(start_cart=(121.1, 27.5), end_cart=(121.3, 29.3))

data = s1.data
xcor = s1.xcor
ycor = s1.ycor
from cinrad.visualize import Section
ax3.contourf(xcor, ycor, data,cmap=cmaps_ref)
ax3.set_ylim(0, 15)
ax3.set_facecolor(color="white")
ax3.set_yticks([0,2,4,6,8,10,12,14])
# ax3.set_yticks([0,2,4,6,8,10,12,14])
ax3.spines['left'].set_color('black')
ax3.spines['bottom'].set_color('black')
ax3.spines['right'].set_color('black')
ax3.spines['top'].set_color('black')
plt.tick_params(axis='x',colors='black')
plt.tick_params(axis='y',colors='black')

**Comment by CyanideCN** [comment]
```python
rl = [f.get_data(i, 230, 'VEL') for i in f.angleindex_r]
```
这一句有问题，angleindex_r是针对反射率的，而你提取的是速度，为了避免错误直接用`list(f.iter_tilt(230, 'VEL'))`更好
