### ISSUE TITLE
用基数据获取VIL和ET数据很慢是为什么？

### ISSUE THREAD

**Issue by MCM-1024** [CyanideCN/PyCINRAD#87]
f = StandardData(r"Z_RADR_I_Z9745_20210702224100_O_DOR_SA_CAP_FMT.bin.bz2")
r1 = list(f.iter_tilt(230, 'REF'))
vil = cinrad.calc.quick_vil(r1)
et = cinrad.calc.quick_et(r1)
-------------------------------------------
运行时间10分钟起步，是我代码有问题吗？

**Comment by CyanideCN** [comment]
纯python实现的算法确实是很慢的，你大概是没有安装cython，所以在安装的时候没有编译速度更快的C扩展。如果是这样的话先安装cython再重新安装cinrad即可

**Comment by MCM-1024** [comment]
请问cython和cinrad的安装顺序有要求吗？
